# Generated by Django 5.2.17 on 2026-09-10 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('classrooms', '0002_jointoken'),
        ('syllabus', '0004_material_failure_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='GeneratedDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('STUDY_PLAN', 'Study Plan')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('content', models.JSONField(help_text='Validated structured JSON output from LLM (syntax validated, factual correctness requires human review).')),
                ('requires_teacher_fact_check', models.BooleanField(default=True, help_text='Explicit indicator that schema validation confirms format only, not factual accuracy.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_draft', to='assessments.assignment')),
                ('approved_quiz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_draft', to='assessments.quiz')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_drafts', to='classrooms.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_drafts', to=settings.AUTH_USER_MODEL)),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_study_plans', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_drafts', to='syllabus.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
