# Generated by Django 5.2.8 on 2026-09-03 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_MATERIAL', 'New Material'), ('DOUBT_REPLY', 'Doubt Reply'), ('DOUBT_ACCEPTED', 'Doubt Answer Accepted'), ('ASSIGNMENT_DUE_SOON', 'Assignment Due Soon'), ('ASSIGNMENT_GRADED', 'Assignment Graded'), ('NEW_QUIZ', 'New Quiz')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
