# Generated by Django 5.2.8 on 2026-09-03 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_state', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('LEARNING', 'Learning'), ('PRACTICING', 'Practicing'), ('COMPLETED', 'Completed'), ('REVIEW_REQUIRED', 'Review Required'), ('MASTERED', 'Mastered')], default='NOT_STARTED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progresses', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='syllabus.topic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'topic'), name='unique_student_topic_progress')],
            },
        ),
    ]
