# Generated by Django 5.2.8 on 2026-09-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
